# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy all files from the current directory to the container
COPY . .

# Build your Vue.js application for production
RUN npm run build

# Expose port 80 for serving the application
EXPOSE 8686

# Define the command to start your application
CMD ["npm", "run", "serve"]
