services:
  app:
    build:
      context: ./Frontend/
    container_name: docker-management-ui
    ports:
      - 8686:80
    restart: unless-stopped

  backend:
    build:
      context: ./Backend/
    container_name: docker-management-server
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    container_name: docker-management-mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
